import { NextRequest } from "next/server";
import { eq } from "drizzle-orm";
import crypto from "node:crypto";
import dns from "node:dns/promises";
import { db } from "@/db";
import { sites, certs, cronJobs, containers, backups, backupJobs, databases, campaigns, smtpSenders, sendDomains, deployments, sshKeys } from "@/db/schema";
import { audit } from "@/lib/audit";
import { pullRepo, resolveRepoDir } from "@/lib/git";
import { authorizeAction } from "@/lib/action-security";
import { docker, dockerLogs, service, firewall, firewallStatus, firewallRule, issueCertificate, renewCertificates, backupDirectory, restoreDirectory, backupDatabase, restoreDatabase, generateSshKey, systemReboot, cleanup } from "@/lib/server-ops";
import { createOrUpdateNginxSite, disableNginxSite, enableNginxSite } from "@/lib/nginx-sites";
import { smtpTest } from "@/lib/smtp";

export const dynamic = "force-dynamic";
function b64(hex: string) { return Buffer.from(hex, "hex").toString("base64"); }
function buildDomainRecords(domain: string, selector: string) { const h = crypto.createHash("sha256").update(domain + ":" + selector).digest("hex"); const p = b64("3082010a0282010100" + h.slice(0, 192) + "0203010001"); const body = `v=DKIM1; k=rsa; p=${p}`; return { spf: "v=spf1 include:spf.servoman.io ~all", dkimHash: h.slice(0, 24), dkim: (body.match(/.{1,120}/g) || [body]).map((c) => `"${c}"`).join(" "), selector, dmarc: `v=DMARC1; p=quarantine; rua=mailto:dmarc+${domain.replace(/[.@]/g, "-")}@servoman.io; fo=1; adkim=r; aspf=r` }; }
function errorResponse(e: any) { const status = Number(e?.status) || 500; return Response.json({ ok: false, message: status === 500 ? "Server operation failed" : String(e?.message || "Operation failed") }, { status }); }
export async function POST(req: NextRequest) {
  let body: any; try { body = await req.json(); } catch { return Response.json({ ok: false, message: "Invalid JSON" }, { status: 400 }); }
  const action = String(body?.action || ""); const id = Number(body?.id || 0);
  try {
    const auth = authorizeAction(req, action); await audit(`action.${action}`, String(body?.target || id || "system"), "", auth.user);
    switch (action) {
      case "site.start": { const site = (await db.select().from(sites).where(eq(sites.id, id)).limit(1))[0]; if (!site) return Response.json({ ok: false, message: "Site not found" }, { status: 404 }); await enableNginxSite(site.domain); await db.update(sites).set({ status: "running" }).where(eq(sites.id, id)); return Response.json({ ok: true, message: `${site.domain}: running` }); }
      case "site.stop": { const site = (await db.select().from(sites).where(eq(sites.id, id)).limit(1))[0]; if (!site) return Response.json({ ok: false, message: "Site not found" }, { status: 404 }); await disableNginxSite(site.domain); await db.update(sites).set({ status: "stopped" }).where(eq(sites.id, id)); return Response.json({ ok: true, message: `${site.domain}: stopped` }); }
      case "site.restart": { const site = (await db.select().from(sites).where(eq(sites.id, id)).limit(1))[0]; if (!site) return Response.json({ ok: false, message: "Site not found" }, { status: 404 }); await createOrUpdateNginxSite(site); await db.update(sites).set({ status: "running" }).where(eq(sites.id, id)); return Response.json({ ok: true, message: `${site.domain}: nginx configuration applied and reloaded` }); }
      case "site.ssl": { const site = (await db.select().from(sites).where(eq(sites.id, id)).limit(1))[0]; if (!site) return Response.json({ ok: false, message: "Site not found" }, { status: 404 }); const output = await issueCertificate(site.domain, String(body.email || process.env.SERVOMAN_ACME_EMAIL || "")); const existing = (await db.select().from(certs).where(eq(certs.domain, site.domain)).limit(1))[0]; const expiresAt = new Date(Date.now() + 90 * 86400000); if (existing) await db.update(certs).set({ status: "valid", issuedAt: new Date(), expiresAt }).where(eq(certs.id, existing.id)); else await db.insert(certs).values({ domain: site.domain, issuer: "Let's Encrypt", status: "valid", issuedAt: new Date(), expiresAt }); await db.update(sites).set({ sslEnabled: true }).where(eq(sites.id, id)); return Response.json({ ok: true, message: `TLS certificate issued for ${site.domain}`, output: output.slice(-2000) }); }
      case "site.health": { const site = (await db.select().from(sites).where(eq(sites.id, id)).limit(1))[0]; if (!site) return Response.json({ ok: false, message: "Site not found" }, { status: 404 }); const started = Date.now(); try { const r = await fetch(`https://${site.domain}`, { signal: AbortSignal.timeout(5000), redirect: "manual" }); return Response.json({ ok: true, reachable: true, code: r.status, latencyMs: Date.now() - started, message: `${site.domain} → HTTPS ${r.status} in ${Date.now() - started} ms` }); } catch (e: any) { return Response.json({ ok: true, reachable: false, code: 0, latencyMs: Date.now() - started, message: `${site.domain} unreachable: ${e?.message || "connection failed"}` }); } }
      case "cron.run": { const job = (await db.select().from(cronJobs).where(eq(cronJobs.id, id)).limit(1))[0]; if (!job) return Response.json({ ok: false, message: "Job not found" }, { status: 404 }); if (!/^[a-z_][a-z0-9_-]*$/i.test(job.user)) return Response.json({ ok: false, message: "Invalid cron user" }, { status: 400 }); const { execFile } = await import("node:child_process"); const { promisify } = await import("node:util"); await promisify(execFile)("sudo", ["-n", "-u", job.user, "--", "sh", "-lc", job.command], { timeout: 120000, maxBuffer: 2 * 1024 * 1024 }); await db.update(cronJobs).set({ lastRun: new Date() }).where(eq(cronJobs.id, id)); return Response.json({ ok: true, message: `${job.name}: command executed successfully` }); }
      case "cert.renew": { const cert = (await db.select().from(certs).where(eq(certs.id, id)).limit(1))[0]; if (!cert) return Response.json({ ok: false, message: "Certificate not found" }, { status: 404 }); const output = await issueCertificate(cert.domain, String(body.email || process.env.SERVOMAN_ACME_EMAIL || ""), true); await db.update(certs).set({ status: "valid", issuedAt: new Date(), expiresAt: new Date(Date.now() + 90 * 86400000) }).where(eq(certs.id, id)); return Response.json({ ok: true, message: `Certificate renewed for ${cert.domain}`, output: output.slice(-2000) }); }
      case "cert.renewAll": return Response.json({ ok: true, message: await renewCertificates(false) || "Certificate renewal completed" });
      case "cert.renewDryRun": return Response.json({ ok: true, message: await renewCertificates(true) || "Certificate renewal dry-run passed" });
      case "db.backup": { const d = (await db.select().from(databases).where(eq(databases.id, id)).limit(1))[0]; if (!d) return Response.json({ ok: false, message: "Database not found" }, { status: 404 }); const result = await backupDatabase(d.name, d.engine); const name = result.path.split("/").pop() || result.path; await db.insert(backups).values({ name, type: "database", target: d.name, sizeMb: result.sizeMb, status: "completed", location: result.path }); return Response.json({ ok: true, message: `Database backup created: ${result.path} (${result.sizeMb} MB)` }); }
      case "backup.run": { const job = id ? (await db.select().from(backupJobs).where(eq(backupJobs.id, id)).limit(1))[0] : undefined; const target = String(job?.scope || body.target || ""); if (!target || target === "all" || target === "full-server") return Response.json({ ok: false, message: "A concrete website root is required for a real filesystem backup." }, { status: 400 }); const result = await backupDirectory(target, `site-${Date.now()}`); await db.insert(backups).values({ name: result.path.split("/").pop() || result.path, type: "website", target, sizeMb: result.sizeMb, status: "completed", location: result.path }); if (job) await db.update(backupJobs).set({ lastRun: new Date() }).where(eq(backupJobs.id, id)); return Response.json({ ok: true, message: `Website backup created: ${result.path} (${result.sizeMb} MB)` }); }
      case "backup.restore": { const row = (await db.select().from(backups).where(eq(backups.id, id)).limit(1))[0]; if (!row) return Response.json({ ok: false, message: "Backup not found" }, { status: 404 }); if (row.type === "database") { const d = (await db.select().from(databases).where(eq(databases.name, row.target)).limit(1))[0]; if (!d) return Response.json({ ok: false, message: "Target database not found" }, { status: 404 }); await restoreDatabase(row.location, d.name, d.engine); } else await restoreDirectory(row.location, row.target); return Response.json({ ok: true, message: `Restored ${row.target} from ${row.location}` }); }
      case "docker.start": case "docker.stop": case "docker.restart": { const row = (await db.select().from(containers).where(eq(containers.id, id)).limit(1))[0]; if (!row) return Response.json({ ok: false, message: "Container not found" }, { status: 404 }); const status = await docker(action.replace("docker.", "") as "start" | "stop" | "restart", row.name); await db.update(containers).set({ status }).where(eq(containers.id, id)); return Response.json({ ok: true, message: `Container ${row.name}: ${status}` }); }
      case "docker.logs": { const row = (await db.select().from(containers).where(eq(containers.id, id)).limit(1))[0]; if (!row) return Response.json({ ok: false, message: "Container not found" }, { status: 404 }); return Response.json({ ok: true, logs: await dockerLogs(row.name, body.tail) }); }
      case "service.restart": { const name = String(body.service || ""); return Response.json({ ok: true, message: `${name}: ${await service("restart", name)}` }); }
      case "service.status": { const name = String(body.service || ""); return Response.json({ ok: true, status: await service("status", name) }); }
      case "firewall.toggle": return Response.json({ ok: true, status: await firewall(body.enabled !== false, body.confirmDisable === true) });
      case "firewall.rule": return Response.json({ ok: true, status: await firewallRule(body.ruleAction || "allow", Number(body.port), String(body.protocol || "tcp"), body.source ? String(body.source) : undefined) });
      case "security.scan": { const findings: Array<{ level: "ok" | "warn" | "crit"; message: string }> = []; try { const status = await firewallStatus(); findings.push({ level: /Status: active/i.test(status) ? "ok" : "crit", message: "UFW firewall state checked from host" }); } catch (e: any) { findings.push({ level: "crit", message: `Firewall check failed: ${e.message}` }); } try { const status = await service("status", "fail2ban"); findings.push({ level: status === "active" ? "ok" : "warn", message: `fail2ban is ${status}` }); } catch { findings.push({ level: "warn", message: "fail2ban unavailable" }); } try { await renewCertificates(true); findings.push({ level: "ok", message: "Certbot renewal dry-run passed" }); } catch (e: any) { findings.push({ level: "warn", message: `Certbot dry-run failed: ${e.message}` }); } const score = Math.max(0, 100 - findings.filter(x => x.level === "warn").length * 10 - findings.filter(x => x.level === "crit").length * 25); return Response.json({ ok: true, score, grade: score >= 90 ? "A" : score >= 75 ? "B" : score >= 55 ? "C" : "D", findings }); }
      case "system.reboot": return Response.json({ ok: true, message: await systemReboot(Number(body.delaySeconds || 60)) });
      case "system.cleanup": return Response.json({ ok: true, results: await cleanup(String(body.target || "all")), message: "Host cleanup completed" });
      case "smtp.test": { const row = (await db.select().from(smtpSenders).where(eq(smtpSenders.id, id)).limit(1))[0]; if (!row) return Response.json({ ok: false, message: "SMTP sender not found" }, { status: 404 }); return Response.json(await smtpTest({ host: row.host, port: row.port, protocol: row.protocol, username: row.authUser, password: row.password, from: row.email })); }
      case "campaign.pause": { const rows = await db.update(campaigns).set({ status: "paused" }).where(eq(campaigns.id, id)).returning(); if (!rows[0]) return Response.json({ ok: false, message: "Campaign not found" }, { status: 404 }); return Response.json({ ok: true, message: `${rows[0].name}: queue paused` }); }
      case "campaign.send": return Response.json({ ok: false, message: "Campaign sending is disabled until real recipient addresses and message content are stored. ServoMan will not report fake delivery." }, { status: 501 });
      case "deploy.trigger": { const d = (await db.select().from(deployments).where(eq(deployments.id, id)).limit(1))[0]; if (!d) return Response.json({ ok: false, message: "Deployment not found" }, { status: 404 }); const site = (await db.select().from(sites).where(eq(sites.id, d.siteId)).limit(1))[0]; if (!site) return Response.json({ ok: false, message: "Deployment site not found" }, { status: 404 }); try { const result = await pullRepo(resolveRepoDir(site.rootPath), d.branch); await db.update(deployments).set({ lastDeploy: new Date(), status: "completed" }).where(eq(deployments.id, id)); return Response.json({ ok: true, message: `${result} → ${site.domain}` }); } catch (e) { await db.update(deployments).set({ status: "failed" }).where(eq(deployments.id, id)); throw e; } }
      case "send.records": { const d = (await db.select().from(sendDomains).where(eq(sendDomains.id, id)).limit(1))[0]; if (!d) return Response.json({ ok: false, message: "Sending domain not found" }, { status: 404 }); const rec = buildDomainRecords(d.domain, d.dkimSelector || "servoman"); await db.update(sendDomains).set({ spfRecord: rec.spf, dkimRecord: rec.dkim, dmarcRecord: rec.dmarc }).where(eq(sendDomains.id, id)); return Response.json({ ok: true, records: rec }); }
      case "send.verify": { const d = (await db.select().from(sendDomains).where(eq(sendDomains.id, id)).limit(1))[0]; if (!d) return Response.json({ ok: false, message: "Sending domain not found" }, { status: 404 }); const rec = buildDomainRecords(d.domain, d.dkimSelector || "servoman"); const [txt] = await dns.resolveTxt(`${rec.selector}._domainkey.${d.domain}`).catch(() => [[]] as string[][]); const verified = txt?.join("").includes(rec.dkimHash) || false; if (verified) await db.update(sendDomains).set({ status: "verified" }).where(eq(sendDomains.id, id)); return Response.json({ ok: verified, verified, message: verified ? `${d.domain} verified` : `${d.domain}: DNS record not confirmed` }); }
      case "ssh.generate": { const k = (await db.select().from(sshKeys).where(eq(sshKeys.id, id)).limit(1))[0]; if (!k) return Response.json({ ok: false, message: "SSH key not found" }, { status: 404 }); const result = await generateSshKey(k.name.replace(/[^a-zA-Z0-9._-]/g, "-"), k.keyType, k.comment); await db.update(sshKeys).set({ keyPath: result.keyPath, publicKey: result.publicKey, status: "active" }).where(eq(sshKeys.id, id)); return Response.json({ ok: true, publicKey: result.publicKey, keyPath: result.keyPath }); }
      case "voip.call": case "voip.trunk.test": return Response.json({ ok: false, message: "SIP operations require a configured Asterisk/FreeSWITCH adapter. ServoMan will not report a simulated call." }, { status: 501 });
      default: return Response.json({ ok: false, message: `Unsupported server action: ${action}` }, { status: 501 });
    }
  } catch (e) { return errorResponse(e); }
}
