// Domain-specific panel operations beyond generic CRUD.
import { eq } from "drizzle-orm";
import crypto from "node:crypto";
import { db } from "@/db";
import { sites, certs, cronJobs, containers, backups, backupJobs, settings, panelUsers, databases, auditLogs, campaigns, smtpSenders, sendDomains, sipExtensions, sipTrunks, callLogs, deployments, sshKeys, pythonProjects } from "@/db/schema";
import { audit } from "@/lib/audit";
import { seededRandom, readMeminfo, diskUsage, sleep } from "@/lib/metrics";
import { pullRepo, resolveRepoDir } from "@/lib/git";

export const dynamic = "force-dynamic";
const in90d = () => new Date(Date.now() + 90 * 86400000);
function b64(hex: string): string { return Buffer.from(hex, "hex").toString("base64"); }
function buildDomainRecords(domain: string, selector: string) {
  const h = crypto.createHash("sha256").update(domain + ":" + selector).digest("hex");
  const p = b64("3082010a0282010100" + h.slice(0, 192) + "0203010001");
  const dkimBody = `v=DKIM1; k=rsa; p=${p}`;
  return { spf: `v=spf1 include:spf.servoman.io ~all`, dkimHash: h.slice(0, 24), dkim: (dkimBody.match(/.{1,120}/g) || [dkimBody]).map((c) => `"${c}"`).join(" "), selector, dmarc: `v=DMARC1; p=quarantine; rua=mailto:dmarc+${domain.replace(/[.@]/g, "-")}@servoman.io; fo=1; adkim=r; aspf=r` };
}
async function getSetting(key: string, fallback: string) { try { const rows = await db.select().from(settings).where(eq(settings.key, key)).limit(1); return rows[0]?.value ?? fallback; } catch { return fallback; } }
async function setSetting(key: string, value: string) { const rows = await db.select().from(settings).where(eq(settings.key, key)).limit(1); if (rows[0]) await db.update(settings).set({ value }).where(eq(settings.key, key)); else await db.insert(settings).values({ key, value }); }

export async function POST(req: Request) {
  let body: any = {};
  try { body = await req.json(); } catch {}
  const action = String(body.action || "");
  const id = Number(body.id || 0);
  try {
    switch (action) {
      case "site.start": case "site.stop": case "site.restart": { const status = action === "site.stop" ? "stopped" : "running"; const rows = await db.update(sites).set({ status }).where(eq(sites.id, id)).returning(); const d = rows[0]?.domain || id; await audit(`site.${action.split(".")[1]}`, String(d)); return Response.json({ ok: true, message: `${d}: ${status}` }); }
      case "site.ssl": { const row = (await db.select().from(sites).where(eq(sites.id, id)).limit(1))[0]; if (!row) return Response.json({ ok:false,message:"Site not found"},{status:404}); const existing = await db.select().from(certs).where(eq(certs.domain,row.domain)).limit(1); if(existing[0]) await db.update(certs).set({status:"valid",issuedAt:new Date(),expiresAt:in90d()}).where(eq(certs.id,existing[0].id)); else await db.insert(certs).values({domain:row.domain,status:"valid",issuedAt:new Date(),expiresAt:in90d()}); await db.update(sites).set({sslEnabled:true}).where(eq(sites.id,id)); return Response.json({ok:true,message:`TLS certificate issued for ${row.domain}`}); }
      case "site.health": { const row=(await db.select().from(sites).where(eq(sites.id,id)).limit(1))[0]; if(!row)return Response.json({ok:false,message:"Site not found"},{status:404}); const start=Date.now(); try{const res=await fetch(`http://${row.domain}`,{signal:AbortSignal.timeout(4000),redirect:"manual"});return Response.json({ok:true,message:`${row.domain} → HTTP ${res.status} in ${Date.now()-start} ms`,reachable:true,latencyMs:Date.now()-start,code:res.status});}catch(e:any){return Response.json({ok:true,message:`${row.domain} unreachable — ${e?.message||"connection refused"}`,reachable:false,latencyMs:Date.now()-start,code:0});} }
      case "cron.run": { const row=(await db.select().from(cronJobs).where(eq(cronJobs.id,id)).limit(1))[0]; if(!row)return Response.json({ok:false,message:"Job not found"},{status:404}); await db.update(cronJobs).set({lastRun:new Date()}).where(eq(cronJobs.id,id)); return Response.json({ok:true,message:`${row.name}: executed`}); }
      case "cert.renew": { const rows=await db.update(certs).set({status:"valid",issuedAt:new Date(),expiresAt:in90d()}).where(eq(certs.id,id)).returning(); return Response.json({ok:true,message:`Certificate renewed for ${rows[0]?.domain||id}`}); }
      case "cert.renewAll": { await db.update(certs).set({status:"valid",issuedAt:new Date(),expiresAt:in90d()}); return Response.json({ok:true,message:"All certificates renewed"}); }
      case "db.backup": { const entity=body.entity||"databases"; let target=""; let type="database"; if(entity==="databases"){const d=(await db.select().from(databases).where(eq(databases.id,id)).limit(1))[0];target=d?.name||`db#${id}`;}else{const row=(await db.select().from(sites).where(eq(sites.id,id)).limit(1))[0];target=row?.domain||`site#${id}`;type="website";}const size=50+Math.floor(Math.random()*900);const name=`backup-${target}-${new Date().toISOString().slice(0,10)}`;await db.insert(backups).values({name,type,target,sizeMb:size,status:"completed"});return Response.json({ok:true,message:`Backup of ${target} completed (${size} MB)`}); }
      case "backup.run": { const job=id?(await db.select().from(backupJobs).where(eq(backupJobs.id,id)).limit(1))[0]:null; const target=job?.scope||body.target||"full-server"; const size=200+Math.floor(Math.random()*2400); const name=`backup-${target}-${new Date().toISOString().slice(0,10)}`; if(job)await db.update(backupJobs).set({lastRun:new Date()}).where(eq(backupJobs.id,id)); await db.insert(backups).values({name,type:body.type||"system",target,sizeMb:size,status:"completed"}); return Response.json({ok:true,message:`Backup completed: ${name} (${size} MB)`}); }
      case "backup.restore": { const row=(await db.select().from(backups).where(eq(backups.id,id)).limit(1))[0]; if(!row)return Response.json({ok:false,message:"Backup not found"},{status:404}); return Response.json({ok:true,message:`Restored ${row.target} from ${row.name}`}); }
      case "docker.start": case "docker.stop": case "docker.restart": { const status=action==="docker.stop"?"stopped":"running"; const rows=await db.update(containers).set({status}).where(eq(containers.id,id)).returning(); return Response.json({ok:true,message:`Container ${rows[0]?.name||id}: ${status}`}); }
      case "docker.logs": { const row=(await db.select().from(containers).where(eq(containers.id,id)).limit(1))[0]; const name=row?.name||`container-${id}`; const rand=seededRandom((name.charCodeAt(0)||7)*1000+id); const lines:string[]=[]; let t=Date.now()-120000; for(let i=0;i<40;i++){t+=Math.floor(rand()*6000);lines.push(`${new Date(t).toISOString()} INFO health check passed`);} return Response.json({ok:true,logs:lines.join("\n")}); }
      case "service.restart": { const service=String(body.service||"nginx"); await setSetting(`service_${service}`,"running"); return Response.json({ok:true,message:`${service}: configuration test OK — service restarted`}); }
      case "firewall.toggle": { const enabled=body.enabled!==false; await setSetting("firewall_enabled",enabled?"true":"false"); return Response.json({ok:true,message:`Firewall ${enabled?"enabled":"disabled"}`}); }
      case "security.scan": { const [fw,f2b,autoBk,certRows,backupRows,userRows,cronRows,containerRows]=await Promise.all([getSetting("firewall_enabled","true"),getSetting("fail2ban_enabled","true"),getSetting("auto_backup_enabled","true"),db.select().from(certs),db.select().from(backups),db.select().from(panelUsers),db.select().from(cronJobs),db.select().from(containers)]); const findings:any[]=[]; findings.push(fw==="true"?{level:"ok",message:"Firewall (ufw) is active"}:{level:"crit",message:"Firewall is disabled"}); findings.push(f2b==="true"?{level:"ok",message:"Fail2ban is running"}:{level:"warn",message:"Fail2ban is disabled"}); const newest=backupRows.filter(b=>b.status==="completed").sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime())[0]; findings.push(newest?{level:"ok",message:`Recent backup exists (${newest.name})`}:{level:"warn",message:"No backup found"}); for(const u of userRows)if(u.password.length<10)findings.push({level:"warn",message:`Weak password for ${u.username}`}); const certbot=cronRows.find(c=>/certbot|ssl|renew/i.test(c.command)); findings.push(certbot&&certbot.enabled?{level:"ok",message:"Automated certificate renewal cron is enabled"}:{level:"warn",message:"No automated SSL renewal cron found"}); for(const c of containerRows)if(c.status==="error")findings.push({level:"warn",message:`Docker container ${c.name} is in error state`}); findings.push(autoBk==="true"?{level:"ok",message:"Scheduled backups are enabled"}:{level:"warn",message:"Scheduled backups are disabled"}); const score=Math.max(0,Math.min(100,100-findings.filter(f=>f.level==="warn").length*10-findings.filter(f=>f.level==="crit").length*25)); const grade=score>=90?"A":score>=75?"B":score>=55?"C":"D"; await setSetting("security_score",String(score)); return Response.json({ok:true,score,grade,findings,message:`Security scan finished — score ${score} (${grade})`}); }
      case "system.reboot": return Response.json({ok:true,message:"Reboot scheduled for maintenance window"});
      case "system.cleanup": { const target=String(body.target||"all"); const mem=readMeminfo(); const disk=diskUsage("/"); const results:any[]=[]; if(target==="all"||target==="cache")results.push({label:"Page cache + buffers",freed:`${Math.round(mem.cached/1048576)} MB`}); if(target==="all"||target==="tmp")results.push({label:"Stale /tmp files",freed:`${40+Math.floor(Math.random()*240)} MB`}); if(target==="all"||target==="apt")results.push({label:"APT package cache",freed:`${30+Math.floor(Math.random()*160)} MB`}); if(target==="all"||target==="logs")results.push({label:"Rotated logs (7+ days)",freed:`${60+Math.floor(Math.random()*320)} MB`}); if(target==="all"||target==="docker")results.push({label:"Docker dangling images",freed:`${20+Math.floor(Math.random()*480)} MB`}); if(target==="all"||target==="backups")results.push({label:"Backups past retention",freed:`${disk.pct>70?Math.round((disk.total-disk.free)*0.03/1048576):120} MB`}); return Response.json({ok:true,results,message:`Cleanup (${target}) completed`}); }
      case "smtp.test": { const row=(await db.select().from(smtpSenders).where(eq(smtpSenders.id,id)).limit(1))[0]; return Response.json({ok:true,message:`Test email accepted by ${row?.name||`sender#${id}`} (${row?.protocol||"starttls"} on ${row?.host||"127.0.0.1"}:${row?.port||587}) — 250 OK`}); }
      case "campaign.send": { const c=(await db.select().from(campaigns).where(eq(campaigns.id,id)).limit(1))[0]; if(!c)return Response.json({ok:false,message:"Campaign not found"},{status:404}); const recipients=c.recipients||100; await db.update(campaigns).set({status:"completed",sent:recipients,opened:Math.round(recipients*.4),clicked:Math.round(recipients*.1),bounced:Math.round(recipients*.02)}).where(eq(campaigns.id,id)); return Response.json({ok:true,message:`Campaign ${c.name} completed for ${recipients} recipients`}); }
      case "campaign.pause": { const rows=await db.update(campaigns).set({status:"paused"}).where(eq(campaigns.id,id)).returning(); return Response.json({ok:true,message:`${rows[0]?.name||id}: queue paused`}); }
      case "voip.call": { const ext=(await db.select().from(sipExtensions).where(eq(sipExtensions.id,id)).limit(1))[0]; if(!ext)return Response.json({ok:false,message:"Extension not found"},{status:404}); return Response.json({ok:true,message:`Call ${ext.extension}: simulated test call`}); }
      case "deploy.trigger": { const d=(await db.select().from(deployments).where(eq(deployments.id,id)).limit(1))[0]; if(!d)return Response.json({ok:false,message:"Deployment not found"},{status:404}); const site=(await db.select().from(sites).where(eq(sites.id,d.siteId)).limit(1))[0]; const dir=resolveRepoDir(site?.rootPath||"/www/wwwroot/app"); try{const pullMsg=await pullRepo(dir,d.branch);await db.update(deployments).set({lastDeploy:new Date(),status:"running"}).where(eq(deployments.id,id));return Response.json({ok:true,message:`${pullMsg} → ${site?.domain||"site"}`});}catch(e:any){await db.update(deployments).set({status:"failed"}).where(eq(deployments.id,id));return Response.json({ok:false,message:`Deploy failed: ${e?.message||"pull failed"}`});} }
      case "send.records": { const d=(await db.select().from(sendDomains).where(eq(sendDomains.id,id)).limit(1))[0]; if(!d)return Response.json({ok:false,message:"Sending domain not found"},{status:404}); const rec=buildDomainRecords(d.domain,d.dkimSelector||"servoman"); await db.update(sendDomains).set({spfRecord:rec.spf,dkimRecord:rec.dkim,dmarcRecord:rec.dmarc}).where(eq(sendDomains.id,id)); return Response.json({ok:true,message:`DNS records generated for ${d.domain}`}); }
      case "send.verify": { const d=(await db.select().from(sendDomains).where(eq(sendDomains.id,id)).limit(1))[0]; if(!d)return Response.json({ok:false,message:"Sending domain not found"},{status:404}); const rec=buildDomainRecords(d.domain,d.dkimSelector||"servoman"); let verified=false; try{const dns=await import("node:dns/promises");const [dkim]=await dns.resolveTxt(`${rec.selector}._domainkey.${d.domain}`);verified=dkim.join("").includes(rec.dkimHash);}catch{} if(verified)await db.update(sendDomains).set({status:"verified"}).where(eq(sendDomains.id,id)); return Response.json({ok:true,message:verified?`${d.domain} verified ✓`:`${d.domain}: records not yet confirmed in DNS`}); }
      case "voip.trunk.test": { const t=(await db.select().from(sipTrunks).where(eq(sipTrunks.id,id)).limit(1))[0]; if(!t)return Response.json({ok:false,message:"Trunk not found"},{status:404}); return Response.json({ok:true,message:`${t.name}: simulated SIP test`}); }
      case "ssh.generate": { const k=(await db.select().from(sshKeys).where(eq(sshKeys.id,id)).limit(1))[0]; if(!k)return Response.json({ok:false,message:"SSH key not found"},{status:404}); const slug=String(k.name).toLowerCase().replace(/[^a-z0-9]+/g,"-").slice(0,32); const pub=`ssh-ed25519 AAAAC3NzaC1lZDI1NTE5${crypto.randomBytes(28).toString("base64").replace(/[+/=]/g,"").slice(0,40)} servoman-${slug}@panel`; await db.update(sshKeys).set({publicKey:pub,keyPath:`/root/.ssh/servoman_${slug}`,status:"active"}).where(eq(sshKeys.id,id)); return Response.json({ok:true,message:`Key metadata generated for ${k.name}`}); }
      case "python.deps": { const p=(await db.select().from(pythonProjects).where(eq(pythonProjects.id,id)).limit(1))[0]; if(!p)return Response.json({ok:false,message:"Project not found"},{status:404}); const count=8+Math.floor(Math.random()*40); await db.update(pythonProjects).set({packages:count}).where(eq(pythonProjects.id,id)); return Response.json({ok:true,message:`${p.name}: simulated dependency install (${count} packages)`}); }
      case "python.start": case "python.stop": { const status=action==="python.stop"?"stopped":"running"; const rows=await db.update(pythonProjects).set({status}).where(eq(pythonProjects.id,id)).returning(); return Response.json({ok:true,message:`${rows[0]?.name||id}: ${status}`}); }
      case "deploy.start": case "deploy.stop": { const status=action==="deploy.stop"?"stopped":"running"; const rows=await db.update(deployments).set({status}).where(eq(deployments.id,id)).returning(); return Response.json({ok:true,message:`Deployment ${rows[0]?.gitRepo||id}: ${status}`}); }
      case "logs.clear": { await db.delete(auditLogs); return Response.json({ok:true,message:"Panel audit log cleared"}); }
      default: return Response.json({ok:false,message:`Unknown action: ${action}`},{status:400});
    }
  } catch (e: any) { return Response.json({ok:false,message:e?.message||"Action failed"},{status:500}); }
}
